# Generated by Django 2.2.4 on 2022-12-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRead', '0002_author_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
