# Generated by Django 2.2.4 on 2023-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRead', '0004_auto_20230102_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
